<?xml version="1.0" encoding="utf-8"?><Database Name="DBFREST" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=DBFREST;Persist Security Info=True;User ID=sa" SettingsObjectName="com.sweetcoffee.Properties.Settings" SettingsPropertyName="DBFRESTConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TRASPALMACEN" Member="TRASPALMACEN">
    <Type Name="TRASPALMACEN">
      <Column Name="SERIE" Type="System.String" DbType="NVarChar(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NUMERO" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LINEA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CODALMORIG" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="CODALMDEST" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="FECHA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CODARTICULO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="REFERENCIA" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="DESCRIPCION" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
      <Column Name="UNIDADES" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PRECIO" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="USUARIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAJA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Z" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STOCK" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DESCARGADO" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="FECHACREACION" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IMPRESIONES" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ESRECUENTO" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OBSERVACIONES" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IDMOTIVO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DESCMOTIVO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>